### ISSUE TITLE
Attacking Help

### ISSUE THREAD

**Issue by tomtomy8** [tomtomy8/Pixel-Crime#3]
I need some help getting the character to attack and generaly how to make the whole brawling system, as I've never done anything like this in Unity.

**Comment by theNimja** [comment]
Yo might want to use animations. Failing that, you'd want to send a Physics.Raycast about 0.5m forward,and, if you hit anything, send it a "You go hit" message

http://www.unity3dstudent.com/2011/02/beginner-b28-sendmessage-to-call-external-functions/
http://www.unity3dstudent.com/2010/08/intermediate-i01-raycasting/

It seems you're using JavaScript, so these tutorials are relevant to you. You might also want to look at the Unity Docs.

**Comment by theNimja** [comment]
Taking the second option, the code I would recommend should be something along the lines of 

function Update () {
 if (<Whatever your inpiut is>){
   var forward= transform.TransformDirection(Vector3.forward);
   var hit : RaycastHit;  
   Debug.DrawRay(transform.position, -up \* 10, Color.green); // or Debug only

   if(Physics.Raycast(transform.position, -forward, hit, 10)){
      Debug.Log("Hit");  
      hit.collider.gameObject.name.sendMessage("hit");

   }
}}

and code in a "Hit()" function to the enemy, so that they will take the message "hit", and do whatever they need to do with it.

PS. I haven't used Unity in a while, and, when I did, I mostly used C#, so my code will probably require some tweaking.

**Comment by tomtomy8** [comment]
Thanks, I've got it now!
